spring:
  redis:
    host: 172.16.88.47
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: rjs123
    url: jdbc:mysql://172.16.88.216:3306/data?characterEncoding=UTF-8
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: debug
server:
  port: 8999

