spring:
  redis:
    host: 127.0.0.1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/data?characterEncoding=UTF-8
  session:
    store-type: redis
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
  data:
    web:
      pageable:
        one-indexed-parameters: true
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: debug
server:
  port: 8999
